# @name login
POST http://localhost:5111/api/login
content-type: application/json

{
    "passkey": "password"
}

###

@token = {{login.response.body.token}}
@noteId = 01HSKYSP75HZY62HX5DS7J1MRG


### Tag Routes

@tagId = someId
POST http://localhost:5111/api/tags
Authorization: {{ token }}
content-type: application/json

{
    "label": "some-thing"
}

###

GET http://localhost:5111/api/tags
Authorization: {{ token }}

###
DELETE http://localhost:5111/api/tags/{{tagId}}
Authorization: {{ token }}

###
GET http://localhost:5111/api/tags/}
Authorization: {{ token }}

### Trending tags
GET http://localhost:5111/api/tags?trending="true"
Authorization: {{ token }}

### Notes Routes
POST http://localhost:5111/api/notes
content-type: application/json
Authorization: {{ token }}

{
    "title":"Some RestTest title",
    "body": "Rest Test",
    "tags":[]
}

###
GET http://localhost:5111/api/notes?q=lorem
Authorization: {{ token }}

###
GET http://localhost:5111/api/notes?latest=true
Authorization: {{ token }}

###
GET http://localhost:5111/api/notes?pinned=true
Authorization: {{ token }}

###

GET http://localhost:5111/api/notes/{{noteId}}}
Authorization: {{ token }}

###
PUT http://localhost:5111/api/notes/{{noteId}}
content-type: application/json
Authorization: {{ token }}

{
  "id": "{{noteId}}",
  "title": "some updated title",
  "body": "note updated, I can believe it",
  "tags": [{"label": "giulioxx"}]
}


###
DELETE http://localhost:5111/api/notes/{{noteId}}
Authorization: {{ token }}

### Archive
POST http://localhost:5111/api/notes/{{noteId}}/archive
Authorization: {{ token }}

### Unarchive
DELETE http://localhost:5111/api/notes/{{noteId}}/archive
Authorization: {{ token }}

### Pin
POST http://localhost:5111/api/notes/{{noteId}}/pin
Authorization: {{ token }}
### Unpin
DELETE http://localhost:5111/api/notes/{{noteId}}/pin
Authorization: {{ token }}