@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDg5NzQ2MjB9.NpX1HiPWlaUy4kUcReIBPB17ZawVjggvedqmoCfwXmQ
@projectId = 01HQJD114TDERTZGYTEA7E6776
###
GET http://localhost:5111/api/projects
Authorization: {{ token }}

###
GET http://localhost:5111/api/projects/{{projectId}}
Authorization: {{ token }}

###
POST http://localhost:5111/api/projects
content-type: application/json
Authorization: {{ token }}

{
    "name":"Some Project",
    "description": "Some stuff and things"
}

### Add Ticket
POST http://localhost:5111/api/projects/{{projectId}}/task
content-type: application/json
Authorization: {{ token }}

{
    "title":"Some Other Task",
    "description": "Some stuff and things",
    "status": "in_progress",
    "tags":[ {"label": "blumbazorg"}]
}

###
PUT http://localhost:5111/api/projects/{{projectId}}
content-type: application/json
Authorization: {{ token }}

{
    "id": "{{projectId}}",
    "name":"Some Project",
    "description": "Some stuff and things",
    "links": [{"href": "http://google.com", "label":"google"}]
}