@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDkyOTQyOTR9.0sYiwPzFtlQAS5AsK-MPsOR7pujSUP7FmEovMtM8MxI
@projectId = 01HQJD00K7HVKP3MFQQWFG4X68
@taskId = 01HQTH10ZVCZQDKTBQD070REZB

###
GET http://localhost:5111/api/projects
Authorization: {{ token }}

###
GET http://localhost:5111/api/projects/{{projectId}}
Authorization: {{ token }}

###
POST http://localhost:5111/api/projects
content-type: application/json
Authorization: {{ token }}

{
    "name":"Onion Rings",
    "description": "Some onion rings maybe, I am not sure",
    "config": { "wip_limit": 4 }
}

### Update Project
PUT http://localhost:5111/api/projects/{{projectId}}
content-type: application/json
Authorization: {{ token }}

{
    "id": "{{projectId}}",
    "name":"Kiffari",
    "description": "Some stuff and things",
    "links": [{"href": "http://google.com", "label":"google"}]
}

### TASKS

### Get Single task
GET http://localhost:5111/api/tasks/{{taskId}}
content-type: application/json
Authorization: {{ token }}

### Add Task
POST http://localhost:5111/api/projects/{{projectId}}/task
content-type: application/json
Authorization: {{ token }}

{
    "title":"Some Other Task",
    "description": "Some stuff and things",
    "status": "in_progress",
    "tags":[ {"label": "blumbazorg"}]
}

### Update Task
PUT http://localhost:5111/api/projects/{{projectId}}/task
content-type: application/json
Authorization: {{ token }}

{
      "id": "01HQKJFEMFFA8SJ99XCDSCNK4T",
      "title": "Some Updated Task",
      "description": "Some stuff and things",
      "status": "backlog",
      "tags": [
        {
          "id": "01HQKJFEMFFA8SJ99XCC42NR59",
          "label": "blumbazorg"
        }, {"label": "not-sure"}
      ]
    }

### Move Task
PUT http://localhost:5111/api/projects/{{projectId}}/task/{{taskId}}/status
content-type: application/json
Authorization: {{ token }}

{
 "status": "in_progress"     
}