###

POST http://localhost:5111/api/notes
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcwODY1NjB9.CiZ1RupTbH-roqgzMW9ccDH33C2cscwrpqjX-l6jvQ4

{
    "title":"Some DueDate title",
    "body": "yet a note, maybe a note",
    "due_date": "2024-02-04T23:04:11.517Z",
    "tags":[]
}

###

GET http://localhost:5111/api/notes?q=lorem
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgzNTc5OTF9.434iNJcjTpqFX55oWLHzUN-DtIULdgcvwxk3RixeCQw
###

GET http://localhost:5111/api/notes?latest=true

###

GET http://localhost:5111/api/notes/01HNTZC5EZWHZY6Z29JEJEZVJ4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcwODY1NjB9.CiZ1RupTbH-roqgzMW9ccDH33C2cscwrpqjX-l6jvQ4

###
PUT http://localhost:5111/api/notes/01HNTZC5EZWHZY6Z29JEJEZVJ4
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcwODY1NjB9.CiZ1RupTbH-roqgzMW9ccDH33C2cscwrpqjX-l6jvQ4

{
  "id": "01HNTZC5EZWHZY6Z29JEJEZVJ4",
  "title": "some updated title",
  "body": "note updated, I can believe it",
  "tags": [{"label": "giulioxx"}]
}


###
DELETE http://localhost:5111/api/notes/01HM92C75FC1STJHN9PT1W3SZ6