version: "3.9"
services:
  db:
    container_name: kato_db
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kato
      POSTGRES_PASSWORD: kato
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
