POST http://localhost:5111/notes
content-type: application/json

{
    "body": "yet a note, maybe a note",
    "tags":[
         {
    "id": "01HM90Z1RTRF44AYD4D9NYFGBK"
  },
  {"label": "mario"}
    ]
}

###

GET http://localhost:5111/notes

###

GET http://localhost:5111/notes/01HMBDV4T4EDEBHC9BTKN5V4X1

###
PUT http://localhost:5111/notes/01HMBDV4T4EDEBHC9BTKN5V4X1
content-type: application/json

{
  "id": "01HMBDV4T4EDEBHC9BTKN5V4X1",
  "body": "yet a note, maybe a note 1133.",
  "tags": [{"label": "giulio"}]
}


###
DELETE http://localhost:5111/notes/01HM92C75FC1STJHN9PT1W3SZ6