###
GET http://localhost:5111/ping

###


POST http://localhost:5111/notes
content-type: application/json
Authorization: user

{
    "title":"Some title",
    "body": "yet a note, maybe a note",
    "tags":[{"label": "jujujvuj"}]
}

###

GET http://localhost:5111/notes
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY3MjI5OTV9.z9jKGvkF7KD-nR9iW257liKXHM_t1nefMG01glJc7KU
###

GET http://localhost:5111/notes?latest=true

###

GET http://localhost:5111/notes/01HMEM1AWS5MRE59QJ5K5VCRP7

###
PUT http://localhost:5111/notes/01HMEM1AWS5MRE59QJ5K5VCRP7
content-type: application/json

{
  "id": "01HMEM1AWS5MRE59QJ5K5VCRP7",
  "title": "some updated title",
  "body": "note updated, I can believe it",
  "tags": [{"label": "giulio"}]
}


###
DELETE http://localhost:5111/notes/01HM92C75FC1STJHN9PT1W3SZ6