POST http://localhost:5111/api/tags
content-type: application/json

{
    "label": "some-thing"
}

###

GET http://localhost:5111/api/tags

###
DELETE http://localhost:5111/api/tags/01HM90Z1RTRF44AYD4D9NYFGBK

###
GET http://localhost:5111/api/tags/01HMHR9Y453CCRTJHT8JREF9DK